"""create document generations table

Revision ID: 977345fb5197
Revises: 
Create Date: 2026-06-29 21:44:13.802793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '977345fb5197'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_generations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('client_name', sa.String(length=100), nullable=False),
    sa.Column('company', sa.String(length=100), nullable=False),
    sa.Column('sector', sa.String(length=80), nullable=False),
    sa.Column('product_service', sa.String(length=150), nullable=False),
    sa.Column('customer_need', sa.Text(), nullable=False),
    sa.Column('document_type', sa.String(length=30), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('tone', sa.String(length=30), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('response', sa.Text(), nullable=False),
    sa.Column('model_name', sa.String(length=50), nullable=True),
    sa.Column('execution_time', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_generations_id'), 'document_generations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_generations_id'), table_name='document_generations')
    op.drop_table('document_generations')
    # ### end Alembic commands ###
